# Generated by Django 3.0.4 on 2020-04-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComicsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.TextField()),
                ('img2', models.TextField()),
                ('img3', models.TextField()),
                ('img4', models.TextField()),
                ('img5', models.TextField()),
                ('img6', models.TextField()),
                ('img7', models.TextField()),
                ('img8', models.TextField()),
                ('img9', models.TextField()),
                ('img10', models.TextField(default=None, null=True)),
                ('img11', models.TextField(default=None, null=True)),
                ('img12', models.TextField(default=None, null=True)),
                ('img13', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.ComicsCategory')),
            ],
        ),
    ]
