# Generated by Django 3.0.4 on 2020-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_comics_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicscontent',
            name='img14',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comicscontent',
            name='img15',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comicscontent',
            name='img16',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comicscontent',
            name='img17',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comicscontent',
            name='img18',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img11',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img12',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img13',
            field=models.TextField(),
        ),
    ]
