# Generated by Django 3.0.4 on 2020-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20200422_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicscontent',
            name='img10',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img11',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img12',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img13',
            field=models.TextField(default=None, null=True),
        ),
    ]
