# Generated by Django 3.0.4 on 2020-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20200422_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='poster',
            field=models.TextField(default=''),
        ),
    ]
