# Generated by Django 3.0.5 on 2020-04-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_comics_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='comics',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img1',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img4',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img5',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img6',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img7',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img8',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comicscontent',
            name='img9',
            field=models.TextField(default=None, null=True),
        ),
    ]
