# Generated by Django 3.0.5 on 2020-04-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_auto_20200426_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comics.ComicsCategory'),
        ),
    ]
